### PR TITLE
Handle image 'object' that is not a string

### PR DESCRIPTION
**Pull request by markbreedlove**
The image record's 'object' property can be an array of strings, or could be missing, or could theoretically be something else we don't expect, like an object.  Handle all of these cases.

Fixes https://issues.dp.la/issues/8539.  The immediate task with this ticket is to take the first element of an array, if 'object' is an array.

### CODE REVIEW

**Comment by AudreyAltman** [comment]
This looks great, very through.  Have you tested it on staging?

**Comment by markbreedlove** [comment]
No, not on staging yet, though I will in a little bit ...

**Comment by anarchivist** [comment]
👍

**Comment by markbreedlove** [comment]
I've tested this on staging now and it looks better. Will follow up with you all ...

**Pull request merged**
