### PR TITLE
Switch to node.js

### PR DESCRIPTION
**Pull request by markbreedlove**
Rewrite to use node.js for better concurrency support.

Also:
- Change Travis config
- Udate .gitignore
- Add .nvmrc for use with nvm
- Specify node 5.10 in Travis config and .nvmrc

### CODE REVIEW

**Comment by markbreedlove** [comment]
I have this feature branch of `automation` that installs the Node version: https://github.com/dpla/automation/compare/feature/change-thumbp-to-node

**Comment by markbreedlove** [comment]
Please note I'll need to squash this before it's merged :-)

**Comment by moltude** [comment]
this also this looks 👍 squash away

**Comment by markbreedlove** [comment]
OK, that's squashed and the tests have passed.

**Pull request merged**
